name: PR checks
on: pull_request

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Run python app
        run: |
          uvicorn app:app &
          sleep 1
          curl --head --fail --retry-delay 1 --retry 30 --retry-connrefused http://localhost

  pack-charm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup LXD
        uses: canonical/setup-lxd@main

      - name: Setup Charmcraft
        run: sudo snap install charmcraft --classic --channel=latest/edge

      - name: Pack charm
        run: |
          cd charm
          charmcraft pack -v --project-dir ./

      - name: Upload charm
        uses: actions/upload-artifact@v4
        with:
          name: cn-ubuntu-com-charm
          path: ./charm/*.charm

  pack-rock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup LXD
        uses: canonical/setup-lxd@main

      - name: Setup Rockcraft
        run: sudo snap install rockcraft --classic --channel=latest/edge

      - name: Pack Rock
        run: rockcraft pack

  lint-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install python dependencies
        run: |
          python3 -m pip install --upgrade pip
          sudo pip3 install ruff

      - name: Lint python
        run: ruff check . --select ALL  --statistics

  test-python:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install requirements
        run: |
          sudo apt-get update && sudo apt-get install --yes python3-setuptools
          sudo pip3 install -r requirements.txt

      - name: Install dependencies
        run: sudo pip3 install coverage

      - name: Run tests with unittest and coverage
        run: |
          coverage run -m unittest discover -s tests
          coverage report -m
